---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    ansible.builtin.package: 
      name: tomcat 
      state: present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    ansible.builtin.package: 
      name: docker 
      state: present
  - name: start docker
    service: name=docker state=started
  - name: install git
    ansible.builtin.package: 
      name: git 
      state: present
  - name: clone a repo
    git: repo=https://github.com/abhay033/myansible1.git dest=/tmp/mygitrepo1
  - name: build docker file
    command: chdir=/tmp/mygitrepo1 docker build -t devopsedu/webapp
  - name: create container
    command: docker run -itd -P devopsedu/webapp

